In [1]:
import pandas as pd
print("Pandas imported successfully, version: "+pd.__version__)
import scipy as sm
from scipy.stats import *
print("SciPy imported successfully, version: "+sm.__version__)
import plotly
print("Plotly imported successfully, version: "+plotly.__version__)
from plotly.graph_objs import * # for importing the different types of plots

from sklearn.decomposition import PCA #For performing principle component analysis

# The following are necessary to run plotly in an offline mode, because its otherwise an online plotting library
from plotly.graph_objs import Scatter, Layout
plotly.offline.init_notebook_mode(connected=True)

Pandas imported successfully, version: 0.23.4
SciPy imported successfully, version: 1.1.0
Plotly imported successfully, version: 3.4.2


In [2]:
#Importuoju savo rats duomenis
data_all = pd.read_csv("/home/emilija/Dokumentai/Magistras/SinBio/Sinbio-projektas/Žiurkių duomenys.csv")

In [3]:
#nope
new_data = data_all.RatPyV1.dropna(inplace=True)

In [4]:
#puiku, pasalina tik tas eiles, kuriose NA yra butent RatPyV1 arba RatPyV2 stulpeliuose 
new_data = data_all.dropna(subset=['RatPyV1', 'RatPyV2'])

In [5]:
new_data.describe(include='all')

Nr     Rūšis                       Vieta Pagavimo_data Lytis  \
count     84        84                          84            84    80   
unique    84         2                          11            37     2   
top     R192  R.rattus  Zarasų raj., Pakniškių km.    2017.09.07  vyr.   
freq       1        57                          48            10    42   
mean     NaN       NaN                         NaN           NaN   NaN   
std      NaN       NaN                         NaN           NaN   NaN   
min      NaN       NaN                         NaN           NaN   NaN   
25%      NaN       NaN                         NaN           NaN   NaN   
50%      NaN       NaN                         NaN           NaN   NaN   
75%      NaN       NaN                         NaN           NaN   NaN   
max      NaN       NaN                         NaN           NaN   NaN   

             Q(g.)       L(mm)     Luo(mm)      P(mm)      A(mm) Amžius  \
count    83.000000   67.000000   67.000000  69.000000  66.000000     84   
unique         NaN         NaN         NaN        NaN        NaN      3   
top            NaN         NaN         NaN        NaN        NaN    ad.   
freq           NaN         NaN         NaN        NaN        NaN     37   
mean    151.337349  169.820896  165.731343  35.391304  18.969697    NaN   
std     115.247906   43.657040   31.582783   5.374825   3.113097    NaN   
min      21.000000   88.000000  101.000000  23.000000  11.000000    NaN   
25%      71.500000  138.500000  134.500000  32.000000  17.000000    NaN   
50%     111.000000  168.000000  172.000000  35.000000  19.000000    NaN   
75%     230.500000  203.500000  191.000000  40.000000  21.000000    NaN   
max     435.000000  249.000000  231.000000  47.000000  27.000000    NaN   

                        Pastabos RatPyV1 RatPyV2  
count                         83      84      84  
unique                         8       2       2  
top     Tvartas, laikomos vištos      Ne      Ne  
freq                          41      74      79  
mean                         NaN     NaN     NaN  
std                          NaN     NaN     NaN  
min                          NaN     NaN     NaN  
25%                          NaN     NaN     NaN  
50%                          NaN     NaN     NaN  
75%                          NaN     NaN     NaN  
max                          NaN     NaN     NaN

In [6]:
# count the number of NaN values in each column
print(new_data.isnull().sum())

Nr                0
Rūšis             0
Vieta             0
Pagavimo_data     0
Lytis             4
Q(g.)             1
L(mm)            17
Luo(mm)          17
P(mm)            15
A(mm)            18
Amžius            0
Pastabos          1
RatPyV1           0
RatPyV2           0
dtype: int64


In [7]:
# count the number of NaN values in each column
print(data_all.isnull().sum())

Nr                0
Rūšis             0
Vieta             0
Pagavimo_data     0
Lytis             5
Q(g.)             1
L(mm)            18
Luo(mm)          18
P(mm)            16
A(mm)            19
Amžius            0
Pastabos          2
RatPyV1          33
RatPyV2          33
dtype: int64


In [8]:
import fancyimpute
print("Fancyimpute imported successfully")
from fancyimpute import IterativeImputer
import numpy

Using TensorFlow backend.


Fancyimpute imported successfully


In [9]:
#data frame with the missings. I keep only floats
df_numeric = new_data.select_dtypes(include=[numpy.float])

In [10]:
#imputuoja dataseto NA reiksmes IterativeImputer: A strategy for imputing missing values by modeling each feature 
#with missing values as a function of other features in a round-robin fashion. 
ip_data=IterativeImputer().fit_transform(df_numeric)

In [11]:
ip_data

array([[ 73.        , 130.        , 158.        ,  33.        ,
         18.        ],
       [ 35.        , 105.        , 127.        ,  28.        ,
         15.        ],
       [ 67.        , 137.        , 149.        ,  34.        ,
         18.        ],
       [102.        , 168.        , 183.        ,  34.        ,
         23.        ],
       [ 86.        , 158.        , 187.        ,  34.        ,
         18.        ],
       [ 55.        , 124.        , 146.        ,  32.        ,
         17.        ],
       [ 79.        , 140.        , 170.        ,  33.        ,
         21.        ],
       [ 35.        , 115.        , 128.        ,  28.        ,
         16.        ],
       [ 32.        , 110.        , 121.        ,  29.        ,
         17.        ],
       [ 35.        , 113.        , 127.        ,  29.        ,
         16.        ],
       [ 21.        ,  88.        , 101.        ,  23.        ,
         15.        ],
       [111.        , 178.6109904 , 202.   

In [12]:
#sutvarko IterativeImputer().fit_transform(df_numeric) outputa i normalia lentele su pavadinimais, kurie buvo pries tai
data=pd.DataFrame(ip_data, columns=df_numeric.columns, index=df_numeric.index)

In [13]:
data

Q(g.)       L(mm)     Luo(mm)      P(mm)      A(mm)
11    73.000000  130.000000  158.000000  33.000000  18.000000
12    35.000000  105.000000  127.000000  28.000000  15.000000
34    67.000000  137.000000  149.000000  34.000000  18.000000
35   102.000000  168.000000  183.000000  34.000000  23.000000
36    86.000000  158.000000  187.000000  34.000000  18.000000
37    55.000000  124.000000  146.000000  32.000000  17.000000
38    79.000000  140.000000  170.000000  33.000000  21.000000
39    35.000000  115.000000  128.000000  28.000000  16.000000
40    32.000000  110.000000  121.000000  29.000000  17.000000
41    35.000000  113.000000  127.000000  29.000000  16.000000
42    21.000000   88.000000  101.000000  23.000000  15.000000
43   111.000000  178.610990  202.000000  38.000000  18.000000
44    28.000000   98.000000  134.000000  29.000000  17.000000
45    30.000000  101.000000  127.000000  27.000000  18.000000
46    45.536869  124.817069  134.000000  30.000000  17.158561
47    32.000000  110.000000  124.000000  30.000000  17.000000
48    24.000000  103.000000  113.000000  26.000000  15.000000
50   351.000000  227.000000  216.000000  42.000000  19.000000
51   421.000000  249.000000  172.000000  42.000000  21.000000
52   384.000000  235.000000  200.000000  41.000000  20.000000
53   285.000000  211.000000  175.000000  39.000000  17.000000
54   292.000000  202.000000  175.000000  40.000000  20.000000
55   433.000000  235.000000  205.000000  45.000000  18.000000
56   435.000000  242.000000  195.000000  44.000000  19.929638
57   408.000000  230.000000  179.000000  42.000000  22.000000
58   332.000000  220.000000  192.000000  40.000000  20.000000
59   105.000000  165.000000  186.000000  32.000000  21.000000
60   111.000000  173.000000  194.000000  33.000000  18.000000
61   107.000000  162.000000  162.000000  33.000000  18.000000
62    98.000000  165.000000  190.000000  35.000000  21.000000
..          ...         ...         ...        ...        ...
87   230.000000  202.000000  201.000000  37.000000  27.000000
88   154.000000  166.673643  165.074978  35.077765  18.914919
89    82.000000  142.749506  153.470559  32.215940  18.431860
90    92.000000  146.072303  155.082284  32.613416  18.498951
91    42.000000  129.458319  147.023659  30.626037  18.163494
92   177.000000  174.316076  168.781946  35.991959  19.069229
93    75.000000  140.423548  152.342351  31.937707  18.384896
94    48.000000  131.451997  147.990694  30.864523  18.203749
95    41.000000  129.126039  146.862486  30.586290  18.156785
96   138.000000  161.357168  162.496218  34.441804  18.807572
97    77.000000  141.088108  152.664696  32.017202  18.398314
98   136.000000  160.692609  162.173873  34.362309  18.794154
99    83.000000  143.081786  153.631731  32.255688  18.438569
100   33.000000  126.467802  145.573106  30.268309  18.103112
101  137.000000  161.024889  162.335046  34.402056  18.800863
102  122.000000  156.040693  159.917459  33.805843  18.700226
103  369.000000  230.000000  199.000000  45.000000  18.000000
104  231.000000  186.000000  174.000000  40.000000  20.000000
105  384.000000  245.000000  200.000000  47.000000  20.000000
106  286.000000  209.000000  185.403075  40.000000  19.788912
107  336.000000  240.000000  160.000000  42.000000  21.000000
108  305.000000  225.000000  190.000000  45.000000  18.000000
109  252.000000  200.000000  170.000000  40.000000  20.000000
110   80.000000  150.000000  115.000000  35.000000  17.000000
111  102.000000  167.000000  125.000000  32.000000  11.000000
112   73.000000  145.000000  120.000000  35.000000  18.000000
113  104.000000  165.000000  160.000000  32.000000  20.000000
114  130.000000  170.000000  176.000000  35.000000  19.000000
115  137.000000  170.000000  195.000000  36.000000  25.000000
116   47.000000  130.000000  135.000000  32.000000  21.000000

[84 rows x 5 columns]

In [14]:
#updeitina dataframe new_data reiksmemis is dataframe data. Reikia, kad sutaptu stulpeliu pavadinimai, 
#tada pakeicia new_data stulpelius su tais pavadinimais i data stulpelius su tais paciais pavadinimais
new_data.update(data)

/home/emilija/Programos/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:5085: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy



In [15]:
new_data

Nr         Rūšis                         Vieta  Pagavimo_data Lytis  \
11   R132      R.rattus    Zarasų raj., Pakniškių km.     2015.08.26  mot.   
12   R133      R.rattus    Zarasų raj., Pakniškių km.     2015.08.26  mot.   
34   R155      R.rattus    Zarasų raj., Pakniškių km.     2014.11.05  mot.   
35   R156      R.rattus      Utenos raj., Vilučių km.     2014.11.17  vyr.   
36   R157      R.rattus    Zarasų raj., Pakniškių km.     2015.10.02  mot.   
37   R158      R.rattus    Zarasų raj., Pakniškių km.     2015.10.02  mot.   
38   R159      R.rattus    Zarasų raj., Pakniškių km.     2015.10.02  vyr.   
39   R160      R.rattus    Zarasų raj., Pakniškių km.     2015.10.03  mot.   
40   R161      R.rattus    Zarasų raj., Pakniškių km.     2015.10.03  vyr.   
41   R162      R.rattus    Zarasų raj., Pakniškių km.     2015.10.12  mot.   
42   R163      R.rattus    Zarasų raj., Pakniškių km.     2015.10.12  mot.   
43   R164      R.rattus    Zarasų raj., Pakniškių km.     2015.10.13  mot.   
44   R165      R.rattus    Zarasų raj., Pakniškių km.     2015.10.13  mot.   
45   R166      R.rattus    Zarasų raj., Pakniškių km.     2015.10.13  mot.   
46   R167      R.rattus    Zarasų raj., Pakniškių km.     2015.10.13  vyr.   
47   R168      R.rattus    Zarasų raj., Pakniškių km.     2015.10.14  vyr.   
48   R169      R.rattus    Zarasų raj., Pakniškių km.     2015.10.14  vyr.   
50   R171  R.norvegicus                 Vilniaus raj.     2015.02.15  vyr.   
51   R172  R.norvegicus                 Vilniaus raj.     2015.02.16  vyr.   
52   R173  R.norvegicus                 Vilniaus raj.     2015.02.17  vyr.   
53   R174  R.norvegicus   Grubupių km., Šilutės raj.      2014.01.03  vyr.   
54   R175  R.norvegicus   Grubupių km., Šilutės raj.      2014.01.03  mot.   
55   R176  R.norvegicus   Grubupių km., Šilutės raj.      2014.01.03  vyr.   
56   R177  R.norvegicus   Grubupių km., Šilutės raj.      2014.01.03  vyr.   
57   R178  R.norvegicus   Grubupių km., Šilutės raj.      2014.01.03  vyr.   
58   R179  R.norvegicus   Grubupių km., Šilutės raj.      2014.01.03  vyr.   
59   R180      R.rattus   Zarasų raj., Antazavės gyv.     2016.01.09  vyr.   
60   R181      R.rattus   Zarasų raj., Antazavės gyv.     2016.01.09  vyr.   
61   R182      R.rattus   Zarasų raj., Antazavės gyv.     2016.01.09  vyr.   
62   R183      R.rattus   Zarasų raj., Antazavės gyv.     2016.01.09  mot.   
..    ...           ...                           ...            ...   ...   
87   R208      R.rattus    Zarasų raj., Pakniškių km.     2016.11.02  vyr.   
88   R209      R.rattus    Zarasų raj., Pakniškių km.  2017.04.05-07  vyr.   
89   R210      R.rattus    Zarasų raj., Pakniškių km.  2017.04.05-07  mot.   
90   R211      R.rattus    Zarasų raj., Pakniškių km.  2017.03.04-07  mot.   
91   R212      R.rattus    Zarasų raj., Pakniškių km.  2017.03.04-07  mot.   
92   R213      R.rattus    Zarasų raj., Pakniškių km.  2017.03.04-07  mot.   
93   R214      R.rattus    Zarasų raj., Pakniškių km.     2017.03.31  vyr.   
94   R215      R.rattus    Zarasų raj., Pakniškių km.     2017.03.31  vyr.   
95   R216      R.rattus    Zarasų raj., Pakniškių km.     2017.03.31  mot.   
96   R217      R.rattus    Zarasų raj., Pakniškių km.     2017.02.20  mot.   
97   R218      R.rattus    Zarasų raj., Pakniškių km.     2017.02.20  mot.   
98   R219      R.rattus    Zarasų raj., Pakniškių km.     2017.05.01  vyr.   
99   R220      R.rattus    Zarasų raj., Pakniškių km.     2017.05.01  mot.   
100  R221      R.rattus    Zarasų raj., Pakniškių km.     2017.02.25  mot.   
101  R222      R.rattus    Zarasų raj., Pakniškių km.     2017.07.08  mot.   
102  R223      R.rattus    Zarasų raj., Pakniškių km.     2017.07.08  mot.   
103  R224  R.norvegicus  Rokiškio raj., Laibgalių km.     2017.09.07  vyr.   
104  R225  R.norvegicus  Rokiškio raj., Laibgalių km.     2017.09.07  mot.   
105  R226  R.norvegicus  Rokiškio raj., Laibgalių km.     2017.09.07  vyr.   
106  R227  R.norvegicus  Roki

In [16]:
# count the number of NaN values in each column
print(new_data.isnull().sum())

Nr               0
Rūšis            0
Vieta            0
Pagavimo_data    0
Lytis            4
Q(g.)            0
L(mm)            0
Luo(mm)          0
P(mm)            0
A(mm)            0
Amžius           0
Pastabos         1
RatPyV1          0
RatPyV2          0
dtype: int64


In [17]:
#nieko cia neisejo, tiek to
df_dummies = pd.get_dummies(new_data['Lytis'])
del df_dummies[df_dummies.columns[-1]]
df_new = pd.concat([new_data, df_dummies], axis=1)
del df_new['Lytis']
df_numeric2 = df_new.select_dtypes(include=[numpy.number])
x = df_numeric2.values
x
correlation_matrix = numpy.corrcoef(x.T)
print(correlation_matrix)

[[ 1.          0.94733762  0.66220002  0.91503214  0.30147838 -0.37576317]
 [ 0.94733762  1.          0.7623498   0.9515901   0.37576278 -0.38838664]
 [ 0.66220002  0.7623498   1.          0.70449988  0.64486579 -0.27722964]
 [ 0.91503214  0.9515901   0.70449988  1.          0.32721074 -0.32478754]
 [ 0.30147838  0.37576278  0.64486579  0.32721074  1.         -0.17744509]
 [-0.37576317 -0.38838664 -0.27722964 -0.32478754 -0.17744509  1.        ]]


In [18]:
df_numeric2

Q(g.)       L(mm)     Luo(mm)      P(mm)      A(mm)  mot.
11    73.000000  130.000000  158.000000  33.000000  18.000000     1
12    35.000000  105.000000  127.000000  28.000000  15.000000     1
34    67.000000  137.000000  149.000000  34.000000  18.000000     1
35   102.000000  168.000000  183.000000  34.000000  23.000000     0
36    86.000000  158.000000  187.000000  34.000000  18.000000     1
37    55.000000  124.000000  146.000000  32.000000  17.000000     1
38    79.000000  140.000000  170.000000  33.000000  21.000000     0
39    35.000000  115.000000  128.000000  28.000000  16.000000     1
40    32.000000  110.000000  121.000000  29.000000  17.000000     0
41    35.000000  113.000000  127.000000  29.000000  16.000000     1
42    21.000000   88.000000  101.000000  23.000000  15.000000     1
43   111.000000  178.610990  202.000000  38.000000  18.000000     1
44    28.000000   98.000000  134.000000  29.000000  17.000000     1
45    30.000000  101.000000  127.000000  27.000000  18.000000     1
46    45.536869  124.817069  134.000000  30.000000  17.158561     0
47    32.000000  110.000000  124.000000  30.000000  17.000000     0
48    24.000000  103.000000  113.000000  26.000000  15.000000     0
50   351.000000  227.000000  216.000000  42.000000  19.000000     0
51   421.000000  249.000000  172.000000  42.000000  21.000000     0
52   384.000000  235.000000  200.000000  41.000000  20.000000     0
53   285.000000  211.000000  175.000000  39.000000  17.000000     0
54   292.000000  202.000000  175.000000  40.000000  20.000000     1
55   433.000000  235.000000  205.000000  45.000000  18.000000     0
56   435.000000  242.000000  195.000000  44.000000  19.929638     0
57   408.000000  230.000000  179.000000  42.000000  22.000000     0
58   332.000000  220.000000  192.000000  40.000000  20.000000     0
59   105.000000  165.000000  186.000000  32.000000  21.000000     0
60   111.000000  173.000000  194.000000  33.000000  18.000000     0
61   107.000000  162.000000  162.000000  33.000000  18.000000     0
62    98.000000  165.000000  190.000000  35.000000  21.000000     1
..          ...         ...         ...        ...        ...   ...
87   230.000000  202.000000  201.000000  37.000000  27.000000     0
88   154.000000  166.673643  165.074978  35.077765  18.914919     0
89    82.000000  142.749506  153.470559  32.215940  18.431860     1
90    92.000000  146.072303  155.082284  32.613416  18.498951     1
91    42.000000  129.458319  147.023659  30.626037  18.163494     1
92   177.000000  174.316076  168.781946  35.991959  19.069229     1
93    75.000000  140.423548  152.342351  31.937707  18.384896     0
94    48.000000  131.451997  147.990694  30.864523  18.203749     0
95    41.000000  129.126039  146.862486  30.586290  18.156785     1
96   138.000000  161.357168  162.496218  34.441804  18.807572     1
97    77.000000  141.088108  152.664696  32.017202  18.398314     1
98   136.000000  160.692609  162.173873  34.362309  18.794154     0
99    83.000000  143.081786  153.631731  32.255688  18.438569     1
100   33.000000  126.467802  145.573106  30.268309  18.103112     1
101  137.000000  161.024889  162.335046  34.402056  18.800863     1
102  122.000000  156.040693  159.917459  33.805843  18.700226     1
103  369.000000  230.000000  199.000000  45.000000  18.000000     0
104  231.000000  186.000000  174.000000  40.000000  20.000000     1
105  384.000000  245.000000  200.000000  47.000000  20.000000     0
106  286.000000  209.000000  185.403075  40.000000  19.788912     1
107  336.000000  240.000000  160.000000  42.000000  21.000000     0
108  305.000000  225.000000  190.000000  45.000000  18.000000     0
109  252.000000  200.000000  170.000000  40.000000  20.000000     1
110   80.000000  150.000000  115.000000  35.000000  17.000000     1
111  102.000000  167.000000  125.000000  32.000000  11.000000     0
112   73.000000  145.000000  120.000000  35.000000  18.000000     0
113  104.000000  165.000000  160.000000  32.000000  20.000000     

In [24]:
a = new_data.reset_index()
df1 = a[a.isnull().any(axis=1)]
df1

index    Nr         Rūšis                       Vieta Pagavimo_data Lytis  \
3     35  R156      R.rattus    Utenos raj., Vilučių km.    2014.11.17  vyr.   
39    72  R193  R.norvegicus  Rokiškio raj., Kovelių km.    2016.04.01   NaN   
40    73  R194  R.norvegicus  Rokiškio raj., Kovelių km.    2016.04.01   NaN   
44    77  R198      R.rattus  Zarasų raj., Pakniškių km.    2016.08.31   NaN   
46    79  R200      R.rattus  Zarasų raj., Pakniškių km.    2016.08.31   NaN   
84    72   NaN           NaN                         NaN           NaN  vyr.   

    Q(g.)  L(mm)     Luo(mm)  P(mm)  A(mm) Amžius                  Pastabos  \
3   102.0  168.0  183.000000   34.0   23.0   sub.                       NaN   
39  314.0  220.0  189.000000   41.0   19.0    ad.                Paukštynas   
40  126.0  165.0  133.000000   36.0   16.0   juv.                Paukštynas   
44  151.0  183.0  189.182949   36.0   22.0    ad.  Tvartas, laikomos vištos   
46   88.0  145.0  167.000000   34.0   21.0   juv.  Tvartas, laikomos vištos   
84    NaN    NaN         NaN    NaN    NaN    NaN                       NaN   

   RatPyV1 RatPyV2  
3       Ne      Ne  
39    Taip      Ne  
40      Ne      Ne  
44      Ne      Ne  
46      Ne      Ne  
84     NaN     NaN

In [29]:
#a = new_data.at['72', 'Lytis'] = "vyr."
#a.set_value('72', 'Lytis', "vyr.")
a.iloc[39, a.columns.get_loc('Lytis')] = "vyr."
df1 = a[a.isnull().any(axis=1)]
df1
#new_data.iloc[72,:]

index    Nr         Rūšis                       Vieta Pagavimo_data Lytis  \
3     35  R156      R.rattus    Utenos raj., Vilučių km.    2014.11.17  vyr.   
40    73  R194  R.norvegicus  Rokiškio raj., Kovelių km.    2016.04.01   NaN   
44    77  R198      R.rattus  Zarasų raj., Pakniškių km.    2016.08.31   NaN   
46    79  R200      R.rattus  Zarasų raj., Pakniškių km.    2016.08.31   NaN   
84    72   NaN           NaN                         NaN           NaN  vyr.   
39   NaN   NaN           NaN                         NaN           NaN  vyr.   
72   NaN   NaN           NaN                         NaN           NaN  vyr.   

    Q(g.)  L(mm)     Luo(mm)  P(mm)  A(mm) Amžius                  Pastabos  \
3   102.0  168.0  183.000000   34.0   23.0   sub.                       NaN   
40  126.0  165.0  133.000000   36.0   16.0   juv.                Paukštynas   
44  151.0  183.0  189.182949   36.0   22.0    ad.  Tvartas, laikomos vištos   
46   88.0  145.0  167.000000   34.0   21.0   juv.  Tvartas, laikomos vištos   
84    NaN    NaN         NaN    NaN    NaN    NaN                       NaN   
39    NaN    NaN         NaN    NaN    NaN    NaN                       NaN   
72    NaN    NaN         NaN    NaN    NaN    NaN                       NaN   

   RatPyV1 RatPyV2  
3       Ne      Ne  
40      Ne      Ne  
44      Ne      Ne  
46      Ne      Ne  
84     NaN     NaN  
39     NaN     NaN  
72     NaN     NaN

In [31]:
a.iloc[39]

index                                    72
Nr                                     R193
Rūšis                          R.norvegicus
Vieta            Rokiškio raj., Kovelių km.
Pagavimo_data                    2016.04.01
Lytis                                  vyr.
Q(g.)                                   314
L(mm)                                   220
Luo(mm)                                 189
P(mm)                                    41
A(mm)                                    19
Amžius                                  ad.
Pastabos                         Paukštynas
RatPyV1                                Taip
RatPyV2                                  Ne
Name: 39, dtype: object

In [41]:
full_data = a.dropna()
no_missing_data_ziurkes = full_data.reset_index()
print(no_missing_data_ziurkes.isnull().sum())

level_0          0
index            0
Nr               0
Rūšis            0
Vieta            0
Pagavimo_data    0
Lytis            0
Q(g.)            0
L(mm)            0
Luo(mm)          0
P(mm)            0
A(mm)            0
Amžius           0
Pastabos         0
RatPyV1          0
RatPyV2          0
dtype: int64


In [42]:
no_missing_data_ziurkes.describe(include="all")

level_0  index    Nr     Rūšis                       Vieta  \
count   80.000000   80.0    80        80                          80   
unique        NaN   80.0    80         2                          10   
top           NaN  116.0  R192  R.rattus  Zarasų raj., Pakniškių km.   
freq          NaN    1.0     1        54                          46   
mean    41.912500    NaN   NaN       NaN                         NaN   
std     24.613567    NaN   NaN       NaN                         NaN   
min      0.000000    NaN   NaN       NaN                         NaN   
25%     20.750000    NaN   NaN       NaN                         NaN   
50%     41.500000    NaN   NaN       NaN                         NaN   
75%     63.250000    NaN   NaN       NaN                         NaN   
max     83.000000    NaN   NaN       NaN                         NaN   

       Pagavimo_data Lytis       Q(g.)       L(mm)     Luo(mm)      P(mm)  \
count             80    80   80.000000   80.000000   80.000000  80.000000   
unique            36     2         NaN         NaN         NaN        NaN   
top       2017.09.07  vyr.         NaN         NaN         NaN        NaN   
freq              10    42         NaN         NaN         NaN        NaN   
mean             NaN   NaN  151.744211  165.380657  164.272802  34.918336   
std              NaN   NaN  117.636167   41.535664   29.110053   5.145127   
min              NaN   NaN   21.000000   88.000000  101.000000  23.000000   
25%              NaN   NaN   65.750000  131.338998  146.646865  31.984427   
50%              NaN   NaN  109.000000  163.500000  163.748109  34.382182   
75%              NaN   NaN  231.500000  197.750000  187.500000  39.250000   
max              NaN   NaN  435.000000  249.000000  231.000000  47.000000   

            A(mm) Amžius                  Pastabos RatPyV1 RatPyV2  
count   80.000000     80                        80      80      80  
unique        NaN      3                         8       2       2  
top           NaN    ad.  Tvartas, laikomos vištos      Ne      Ne  
freq          NaN     36                        39      70      75  
mean    18.809298    NaN                       NaN     NaN     NaN  
std      2.752830    NaN                       NaN     NaN     NaN  
min     11.000000    NaN                       NaN     NaN     NaN  
25%     18.000000    NaN                       NaN     NaN     NaN  
50%     18.468760    NaN                       NaN     NaN     NaN  
75%     20.000000    NaN                       NaN     NaN     NaN  
max     27.000000    NaN                       NaN     NaN     NaN

In [43]:
no_missing_data_ziurkes.describe()

level_0       Q(g.)       L(mm)     Luo(mm)      P(mm)      A(mm)
count  80.000000   80.000000   80.000000   80.000000  80.000000  80.000000
mean   41.912500  151.744211  165.380657  164.272802  34.918336  18.809298
std    24.613567  117.636167   41.535664   29.110053   5.145127   2.752830
min     0.000000   21.000000   88.000000  101.000000  23.000000  11.000000
25%    20.750000   65.750000  131.338998  146.646865  31.984427  18.000000
50%    41.500000  109.000000  163.500000  163.748109  34.382182  18.468760
75%    63.250000  231.500000  197.750000  187.500000  39.250000  20.000000
max    83.000000  435.000000  249.000000  231.000000  47.000000  27.000000

In [44]:
no_missing_data_ziurkes.to_csv('Pilni_ziurkiu_duomenys.csv')